name: Test and lint
on: [push]
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install 🔧
        run: cd packages/prong && yarn

      - name: Test
        run: cd packages/prong && yarn test

      - name: Lint
        run: cd packages/prong && yarn lint
