name: Test and lint
on: [push]
paths:
  - "packages/prong"
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install 🔧
        run: yarn

      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint
