name: Test and lint
on: [push]
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install 🔧
        run: yarn
        working-directory: ./packages/prong

      - name: Test 🔬
        run: yarn test
        working-directory: ./packages/prong

      - name: Lint 🧵
        run: yarn lint
        working-directory: ./packages/prong
